Entrega1+BaldoTessa/blogcurso/blogcurso/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cursosapp/', include('cursosapp.urls'))
    
]

Entrega1+BaldoTessa/blogcurso/cursosapp/urls.py
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    path('', views.index, name= "index"),
    path('cursos/', cursos, name="cursos" ),
    path('crear_curso/', crear_curso, name="crear_curso" ),
    path('buscar_curso/', buscar_curso, name="buscar_curso"),
    path('profesores/', profesores, name="profesores"),
    path('crear_profesor/', crear_profesor, name="crear_profesor" ),
    path('buscar_profesor/', buscar_profesor, name="buscar_profesor"),
    path('alumnos/', alumnos, name="alumnos"),
    path('crear_alumno/', crear_alumno, name="crear_alumno" ),
    path('buscar_alumno/', buscar_alumno, name="buscar_alumno"),
    path('base/', base),
   
]

Entrega1+BaldoTessa/blogcurso/cursosapp/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

class Curso(models.Model):
    nombrecurso = models.CharField("Nombre del Curso", max_length=30)
    profesor = models.CharField("Nombre del Profesor", max_length=30)
    comision = models.PositiveIntegerField("Comision")
    diascurso = models.CharField("Dias de cursada", max_length=30)
    
class Profesor(models.Model):
    nombreprofesor = models.CharField("Nombre del profesor", max_length= 35)
    edad = models.PositiveSmallIntegerField("Edad del Profesor")
    NIVELES =(
        (1, "Basico"),
        (2, "Intermedio"),
        (3, "Avanzado")
    )
    nivel = models.PositiveSmallIntegerField("Nivel", choices= NIVELES)
    
class Alumno(models.Model):
    nombrealumno = models.CharField("Nombre del alumno", max_length= 35)
    edad = models.PositiveSmallIntegerField("Edad del Alumno")
    cursosrealizados = models.PositiveSmallIntegerField("Cursos Realizados")
    telefono = models.PositiveIntegerField("Numero telefonico alumno")
    
    

Entrega1+BaldoTessa/blogcurso/cursosapp/views.py
from django.shortcuts import redirect, render
from .models import Curso
from .models import Profesor
from .models import Alumno

def index(request):
    return render(request, "cursosapp/index.html")

def cursos(request):
    cursos = Curso.objects.all() 
    return render(request, "cursosapp/cursos.html", {"cursos": cursos})

def crear_curso(request):

    if request.method == "GET":
        return render(request, "cursosapp/formulario_curso.html", {})
    elif request.method == "POST":
        info_formulario = request.POST
        curso = Curso(nombrecurso=info_formulario["nombrecurso"], profesor=info_formulario["profesor"], comision=info_formulario["comision"], diascurso=info_formulario["diascurso"])
        curso.save()
        return redirect("cursos")
    else:
         return render(request, "cursosapp/formulario_curso.html", {})

def buscar_curso(request):

    if request.method == "POST":

        info_curso = request.POST["curso"]
        
        cursos = Curso.objects.filter(nombrecurso__icontains=info_curso).values()
        

        return render(request,"cursosapp/buscar_curso.html",{"cursos":cursos})

    else: # get y otros

        cursos =  []  #Curso.objects.all()
        
        return render(request,"cursosapp/buscar_curso.html",{"cursos":cursos})


def profesores(request):
    profesores = Profesor.objects.all()
    return render(request, "cursosapp/profesores.html", {"profesores": profesores} )

def crear_profesor(request):

    if request.method == "GET":
        return render(request, "cursosapp/formulario_profesor.html", {})
    elif request.method == "POST":
        info_profesor = request.POST
        curso = Profesor(nombreprofesor=info_profesor["nombreprofesor"], edad=info_profesor["edad"], nivel=info_profesor["nivel"])
        curso.save()
        return redirect("profesores")
    else:
         return render(request, "cursosapp/formulario_profesor.html", {})

def buscar_profesor(request):

    if request.method == "POST":

        info_profe = request.POST["profesor"]
        
        profesores = Profesor.objects.filter(nombreprofesor__icontains=info_profe).values()
        

        return render(request,"cursosapp/buscar_profesor.html",{"profesores":profesores})

    else: # get y otros

        profesores =  []  #Curso.objects.all()
        
        return render(request,"cursosapp/buscar_profesor.html",{"profesores":profesores})


def alumnos(request):
    alumnos = Alumno.objects.all()
    return render(request, "cursosapp/alumnos.html", {"alumnos": alumnos} )
 
def crear_alumno(request):

    if request.method == "GET":
        return render(request, "cursosapp/formulario_alumno.html", {})
    elif request.method == "POST":
        info_alumno = request.POST
        curso = Alumno(nombrealumno=info_alumno["nombrealumno"], edad=info_alumno["edad"], cursosrealizados=info_alumno["cursosrealizados"], telefono=info_alumno["telefono"])
        curso.save()
        return redirect("alumnos")
    else:
         return render(request, "cursosapp/formulario_alumno.html", {})

def buscar_alumno(request):

    if request.method == "POST":

        info_alum = request.POST["alumno"]
        
        alumnos = Alumno.objects.filter(nombrealumno__icontains=info_alum).values()
        

        return render(request,"cursosapp/buscar_alumno.html",{"alumnos":alumnos})

    else: # get y otros

        alumnos =  []  
        
        return render(request,"cursosapp/buscar_alumno.html",{"alumnos":alumnos})




def base(request):
    return render(request, "cursosapp/base.html", {})    




Entrega1+BaldoTessa/blogcurso/blogcurso/templates/cursos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
</head>
<body>
    <h1>CURSOS:</h1>
    <h2>Estos son los cursos que dictaremos:</h2>
    <ul>
        {% for curso in cursos %}
        <li> {{curso.nombre}} </li>
        <li> {{curso.profesor}} </li>
        <li> {{curso.comision}} </li>
        <li> {{curso.diascurso}} </li>
        {% endfor %}
        
    </ul>
</body>
</html>

Entrega1+BaldoTessa/blogcurso/blogcurso/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cursos</title>
</head>
<body>
    <h2>Hola nosotros somos los cursos</h2>
</body>
</html>

Entrega1+BaldoTessa/blogcurso/blogcurso/templates/profesores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profesores</title>
</head>
<body>
    <h1>PROFESORES:</h1>
    <h2>Estos son nuestros profesores:</h2>
    <ul>
        {% for profesor in profesores %}
        <li> {{profesor.nombreprofesor}} </li>
        <li> {{profesor.edad}} </li>
        <li> {{profesor.nivel}} </li>
      
        {% endfor %}
        
    </ul>
</body>
</html>

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/alumnos.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Alumnos
{% endblock %} 

{% block contenidoPagina %} 

<section class="bg-light py-5">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div style="text-align:right">
                    <a href="/cursosapp/buscar_alumno/"><button>Buscar alumno</button></a>
               </div>
                <h5 style="color: palevioletred">Los Alumnos son:</h5>
               
                    <ul class="list-group list-group">
                    
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                        
                            
                
                            <b>Nombre del alumno</b>   <!-- Encabezados-->
                            <b>Edad</b>
                            <b>Cursos realizados</b>
                            <b>Telefono</b>

                        </li>

        
                            {% for alumno in alumnos %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">


                            <span>{{alumno.nombrealumno}}</span>
                            <span>{{alumno.edad}}</span>
                            <span>{{alumno.cursosrealizados}}</span>
                            <span>{{alumno.telefono}}</span>
                        
                        </li>
                       
                    {% endfor %}
                
                    </ul>
                    <br>
                        <div style="text-align:right">
                             <a href="/cursosapp/crear_alumno/"><button>Ingresar nuevo alumno</button></a>
                        </div>
                       
            </div>
        </div>
    </div>
        

</section>
{% endblock %} 









<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumnos</title>
</head>
<body>
    <h1>Alumnos:</h1>
    <ul>
        {% for alumno in alumnos %}
        <li>{{alumno.nombrealumno}}</li>
        <li>{{alumno.edad}}</li>
        <li>{{alumno.cursosrealizados}}</li>
        <li>{{alumno.telefono}}</li>
        {% endfor %}
    </ul>
</body>
</html>

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block tituloPagina %} {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' }" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Coder App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/cursosapp/">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="/cursosapp/cursos/">Cursos</a></li>
                        <li class="nav-item"><a class="nav-link" href="/cursosapp/profesores/">Profesores</a></li>
                        <li class="nav-item"><a class="nav-link" href="/cursosapp/alumnos/">Alumnos</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-5">
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">Cursos App</h1> 
                        </div>
                    </div>
                </div>
            </div>
        </header>
       
        {% block contenidoPagina %}

        {% endblock %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-5"><p style="color: palevioletred" class="m-0 text-center">Copyright &copy; CursosAPP2022 - Lucila Tessa & Luciana Baldo</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/buscar_alumno.html
{% extends 'cursosapp/base.html' %}
{% load static %}

{% block tituloPagina %}
Buscar Alumno
{% endblock %}

{% block contenidoPagina %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-6">
        <p><h3>Buscar alumno:</h3>
             <form action="" method="post">
             {% csrf_token %}

                <input type="text" name="alumno" id="" min="0">

                 <input type="submit" value="Buscar">
            </form>
        </p>

    
        <h5 style="color: palevioletred ">Resultados: </h5>
        <ul class="list-group list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                                
              <b>Nombre del alumno</b>  <!-- Encabezados-->
              <b>Edad</b>
              <b>Cursos realizados</b>
              <b>Telefono</b>

            </li>

            {% for resultado in alumnos %}
             <li class="list-group-item d-flex justify-content-between align-items-start">
                 <p>{{resultado.nombrealumno}} </p>
                 <p>{{resultado.edad}}</p>
                 <p>{{resultado.cursosrealizados}}</p> 
                 <p>{{resultado.telefono}}</p> 

             </li>
            {% endfor %}
        </ul>
    </div>
</div>
<br>
<br>
{% endblock %}

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/buscar_curso.html
{% extends 'cursosapp/base.html' %}
{% load static %}

{% block tituloPagina %}
Buscar Curso
{% endblock %}

{% block contenidoPagina %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-6">
        <p><h3>Buscar curso:</h3>
             <form action="" method="post">
             {% csrf_token %}

                <input type="text" name="curso" id="" min="0">

                 <input type="submit" value="Buscar">
            </form>
        </p>

    
        <h5 style="color: palevioletred ">Resultados: </h5>
        <ul class="list-group list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                                
                                    
              <b>Curso</b> <!-- Encabezados-->
              <b>Nombre del profesor</b>  
              <b>Numero de comision</b>
              <b>Dias de cursada</b>
    
            </li>

            {% for resultado in cursos %}
             <li class="list-group-item d-flex justify-content-between align-items-start">
                 <p>{{resultado.nombrecurso}} </p>
                 <p> {{resultado.profesor}} </p>
                 <p>  {{resultado.comision}}</p> 
                 <p>  {{resultado.diascurso}}</p>
             </li>
            {% endfor %}
        </ul>
    </div>
</div>
<br>
<br>
{% endblock %}

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/buscar_profesor.html
{% extends 'cursosapp/base.html' %}
{% load static %}

{% block tituloPagina %}
Buscar Profesor
{% endblock %}

{% block contenidoPagina %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-6">
        <p><h3>Buscar profesor:</h3>
             <form action="" method="post">
             {% csrf_token %}

                <input type="text" name="profesor" id="" min="0">

                 <input type="submit" value="Buscar">
            </form>
        </p>

    
        <h5 style="color: palevioletred" >Resultados: </h5>
        <ul class="list-group list-group">
            <li class="list-group-item d-flex justify-content-between align-items-start">
                                
              <b>Nombre del profesor</b>  <!-- Encabezados-->
              <b>Nivel</b>
              <b>Edad</b>
    
            </li>

            {% for resultado in profesores %}
             <li class="list-group-item d-flex justify-content-between align-items-start">
                 <p> {{resultado.nombreprofesor}} </p>
                 <p> {{resultado.nivel}} </p> 
                 <p>{{resultado.edad}}</p>
             </li>
            {% endfor %}
        </ul>
    </div>
</div>
<br>
<br>
{% endblock %}

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/cursos.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Cursos
{% endblock %} 

{% block contenidoPagina %} 

        <section class="bg-light py-5">
            <div class="container px-5" >
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div style="text-align:right">
                            <a href="/cursosapp/buscar_curso/"><button>Buscar curso</button></a>
                       </div>
                        <h5 style="color: palevioletred" >Los cursos son:</h5>
                       
                            <ul class="list-group list-group">
                            
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                
                                    
                                    <b>Curso</b> <!-- Encabezados-->
                                    <b>Nombre del profesor</b>  
                                    <b>Numero de comision</b>
                                    <b>Dias de cursada</b>
                                    
                                </li>

                                {% for curso in cursos %}
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                    
                                     <span >{{curso.nombrecurso}}</span>
                                     <span >{{curso.profesor}}</span>
                                     <span >{{curso.comision}}</span>
                                     <span >{{curso.diascurso}}</span>
                                
                                </li>
                               
                            {% endfor %}
                        
                            </ul>
                            <br>
                                <div style="text-align:right">
                                     <a href="/cursosapp/crear_curso/"><button>Ingresar nuevo curso</button></a>
                                </div>
                               
                    </div>
                </div>
            </div>
                

        </section>
        {% endblock %} 
       
       




Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/formulario_alumno.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Ingresar Alumno
{% endblock %} 

{% block contenidoPagina %} 

<section class="bg-light py-5">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <h2 style="color: palevioletred" >Ingresa un nuevo alumno:</h2>
                    <form action="" method="post">
                     {% csrf_token %}

                     <p>Nombre del Alumno: <input type="text" name="nombrealumno" id=""></p>
                     <p>Edad: <input type="number" name="edad" id=""></p>
                     <p>Cursos realizados: <input type="number" name="cursosrealizados" id=""></p>
                     <p>Telefono: <input type="number" name="telefono" id=""></p>

                     <input type="submit" value="Ingresar Alumno">
                    </form>
            </div>
        </div>
    </div>
</section>

{% endblock %} 

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/formulario_curso.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Ingresar Curso
{% endblock %} 

{% block contenidoPagina %} 

<section class="bg-light py-5">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <h2 style="color: palevioletred" >Ingresa un nuevo curso:</h2>
                    <form action="" method="post">
                     {% csrf_token %}

                     <p>Curso: <input type="text" name="nombrecurso" id=""></p>
                     <p>Profesor: <input type="text" name="profesor" id=""></p>
                     <p>Comision: <input type="number" name="comision" id=""></p>
                     <p>Dias de cursada: <input type="text" name="diascurso" id=""></p>

                     <input type="submit" value="Ingresar Curso">
                    </form>
            </div>
        </div>
    </div>
</section>

{% endblock %} 

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/formulario_profesor.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Ingresar Profesor
{% endblock %} 

{% block contenidoPagina %} 

<section class="bg-light py-5">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <h2 style="color: palevioletred" >Ingresa un nuevo profesor:</h2>
                    <form action="" method="post">
                     {% csrf_token %}

                     <p>Nombre del Profesor: <input type="text" name="nombreprofesor" id=""></p>
                     <p>Nivel: <input type="number" name="nivel" id=""></p>
                     <p>Edad: <input type="number" name="edad" id=""></p>

                     <input type="submit" value="Ingresar Profesor">
                    </form>
            </div>
        </div>
    </div>
</section>

{% endblock %} 

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/index.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
<h1>Bienvenidos</h1>
{% endblock %} 


{% block contenidoPagina %} 

<center> 
    <img src="https://img.freepik.com/vector-gratis/banner-codificacion-programacion-desarrollo-web-codigo-computadora-ilustracion-vectorial_3482-6652.jpg?w=1480" alt="Imagen código"> 
</center>


<center><h2 style="color:grey">¿Quienes somos?
</h2></center>

<center><p>
    <h3 style="color:palevioletred" >  Somos una institución dedicada a brindarle la mejor opción al estudiante de I.T. 
    Con una plataforma única, para poder facilitar su aprendizaje y su accesibilidad a la información.</h3>
</p></center>
{% endblock %} 

Entrega1+BaldoTessa/blogcurso/cursosapp/templates/cursosapp/profesores.html
{% extends 'cursosapp/base.html' %}
{% load static %} 

{% block tituloPagina %} 
Profesores
{% endblock %} 

{% block contenidoPagina %} 

<section class="bg-light py-5">
    <div class="container px-5" >
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <div style="text-align:right">
                    <a href="/cursosapp/buscar_profesor/"><button>Buscar profesor</button></a>
               </div>
                <h5 style="color: palevioletred" >Los Profesores son:</h5>
               
                    <ul class="list-group list-group">
                    
                        <li class="list-group-item d-flex justify-content-between align-items-start">
                        
                            
                
                            <b>Nombre del profesor</b>   <!-- Encabezados-->
                            <b>Nivel</b>
                            <b>Edad</b>
                            
                        </li>

        
                            {% for profesor in profesores %}
                            <li class="list-group-item d-flex justify-content-between align-items-start">


                            <span>{{profesor.nombreprofesor}}</span>
                              <span>{{profesor.get_nivel_display}}</span>
                              <span>{{profesor.edad}}</span>
                            
                        
                        </li>
                       
                    {% endfor %}
                
                    </ul>
                    <br>
                        <div style="text-align:right">
                             <a href="/cursosapp/crear_profesor/"><button>Ingresar nuevo profesor</button></a>
                        </div>
                       
            </div>
        </div>
    </div>
        

</section>
{% endblock %} 






